services:
  panel:
    image: ghcr.io/pterodactyl/panel:v1.14.1
    restart: unless-stopped

    volumes:
      - "${PANEL_DATA_DIR}/var:/app/var"
      - "${PANEL_DATA_DIR}/logs:/app/storage/logs"
      - "${PANEL_DATA_DIR}/nginx:/etc/nginx/http.d"

    networks:
      - http-proxy
      - internal

    labels:
      caddy: "${PANEL_DOMAIN}"
      caddy.reverse_proxy: "{{upstreams 80}}"

    environment:
      APP_KEY: "${APP_KEY}"
      APP_ENV: "${APP_ENV}"
      APP_ENVIRONMENT_ONLY: "${APP_ENVIRONMENT_ONLY}"
      APP_URL: "${APP_URL}"
      APP_TIMEZONE: "${APP_TIMEZONE}"
      APP_SERVICE_AUTHOR: "${APP_SERVICE_AUTHOR}"

      DB_CONNECTION: "${DB_CONNECTION}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"

      CACHE_DRIVER: "${CACHE_DRIVER}"
      SESSION_DRIVER: "${SESSION_DRIVER}"
      QUEUE_DRIVER: "${QUEUE_DRIVER}"

      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"

    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:alpine
    restart: unless-stopped

    networks:
      - internal

    command: >
      redis-server
      --requirepass "${REDIS_PASSWORD}"

    volumes:
      - "${REDIS_DATA_DIR}:/data"

networks:
  http-proxy:
    external: true

  internal: