services:
  livekit:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    command: --config /etc/livekit.yaml

    environment:
      LIVEKIT_KEYS: "${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"

    volumes:
      - "${LIVEKIT_CONFIG_PATH}:/etc/livekit.yaml:ro"

    ports:
      - "${LIVEKIT_HTTP_PORT}:7880"
      - "${LIVEKIT_RTC_TCP_PORT}:7881"
      - "${LIVEKIT_RTC_UDP_PORT}:7882/udp"